#! /bin.bash
#######list of strings will be stored in array####
FRUITS=("apple","orange","kiwi")
#echo "fruits=$fruits"
echo "all args passed to array=$@"
echo "no of args prsent=$#"
echo "frutis are=${FRUITS[@]}"
echo "frui1=${FRUITS[0]}"